# Generated by Django 5.0.6 on 2024-06-21 15:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0003_freeproduct'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='freeproduct',
            options={'verbose_name': 'FreeProduct', 'verbose_name_plural': 'FreeProducts'},
        ),
        migrations.AlterModelOptions(
            name='product',
            options={'verbose_name': 'Products', 'verbose_name_plural': 'Products'},
        ),
    ]
