# Generated by Django 4.2.3 on 2024-06-24 15:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0007_remove_product_content_en_remove_product_name_en'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='product',
            options={'verbose_name': 'Mahsulot', 'verbose_name_plural': 'Mahsulotlar'},
        ),
    ]
