# Generated by Django 4.2.3 on 2024-06-26 10:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0009_alter_freeproduct_created_at_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='content_ru',
        ),
        migrations.RemoveField(
            model_name='product',
            name='content_uz',
        ),
        migrations.RemoveField(
            model_name='product',
            name='name_ru',
        ),
        migrations.RemoveField(
            model_name='product',
            name='name_uz',
        ),
    ]
