# Generated by Django 4.2.3 on 2024-06-24 15:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0003_user_lang'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='username',
        ),
    ]
