# Generated by Django 4.2.3 on 2024-06-21 13:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('product', '0003_freeproduct'),
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('count', models.IntegerField(default=0)),
                ('free_count', models.IntegerField(default=0)),
                ('longitude', models.FloatField()),
                ('latitude', models.FloatField()),
                ('status', models.BooleanField(default=False)),
                ('status_change', models.BigIntegerField()),
                ('product_price', models.BigIntegerField()),
                ('total_price', models.BigIntegerField()),
                ('costumer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user.user')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='product.product')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
